# Site settings
title: Royall Design
description: A Modern Design Studio.
keywords: Modern, Design, Fun
author: Royall Design
baseurl: "" # the subpath of your site, e.g. /blog/
url: "tirelesswake.github.io/royall/" # the base hostname & protocol for your site
